---
- name: Install Windows updates
  hosts: role_windows_server

  tasks:
    - name: Install updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: true
